# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo01(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1050, 708)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,350)")
    self.driver.close()
  
  def test_demo02(self):
    self.driver.get("https://ceshiren.com/")
    self.driver.set_window_size(1050, 708)
    self.driver.execute_script("window.scrollTo(0,350)")
    self.driver.close()
  
